from faker import Faker

fake = Faker()


def random_fact() -> str:
    """
    :return: Returns a random fact generated by Faker
    """

    generated_fact: str = fake.text()
    return generated_fact


fact: str = random_fact()
print(f"Random fact: \n{fact}")
